/**
 * Custom worker entrypoint.
 *
 * OpenNext generates `.open-next/worker.js` with a `fetch` handler and the
 * Durable Object classes below. This file exists only to re-export them
 * under a stable path so `wrangler.jsonc`'s `main` can point here instead
 * of directly at the generated file.
 *
 * This used to also implement `scheduled`, POSTing signed self-requests to
 * /api/crm/tick and /api/social/tick every five minutes via a Cloudflare
 * cron. Both routes were deleted along with the CRM and social modules on
 * this branch; wrangler.jsonc's `triggers` block kept firing the cron
 * regardless, at 288 invocations a day, each one logging a 404 — a
 * permanent false error signal in the place you'd look first when
 * something real breaks. Removed along with `triggers` in wrangler.jsonc.
 */
// `.open-next/worker.js` is generated by `opennextjs-cloudflare build`, which
// runs AFTER `next build` — so it never resolves during the type-check step of
// the build that creates it. tsconfig's `exclude` cannot prevent this:
// `wrangler types` writes `typeof import("./worker")` into cloudflare-env.d.ts,
// so this file is pulled back in as a transitive dependency. Wrangler bundles
// the real module at deploy time.
// @ts-expect-error -- generated at build time
import openNextHandler from "./.open-next/worker.js";

// @ts-expect-error -- generated at build time
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

export default {
  fetch: openNextHandler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
